
"""SECTION: WEATHER IDs.
Obtained from https://openweathermap.org/weather-conditions"""
WEATHER_ID_CLEAR = 800

WEATHER_ID_FEW_CLOUDS = 801
WEATHER_ID_SCATTERED_CLOUDS = 802
WEATHER_ID_BROKEN_CLOUDS = 803
WEATHER_ID_OVERCAST_CLOUDS = 804

WEATHER_GROUP_CLOUDS = (
    WEATHER_ID_FEW_CLOUDS,
    WEATHER_ID_SCATTERED_CLOUDS,
    WEATHER_ID_BROKEN_CLOUDS,
    WEATHER_ID_OVERCAST_CLOUDS
)

WEATHER_ID_CALM = 951

# Contains every weather ID that represents that it isn't raining
WEATHER_GROUP_GOOD_WEATHER = (
    WEATHER_ID_CLEAR,
    WEATHER_ID_FEW_CLOUDS,
    WEATHER_ID_SCATTERED_CLOUDS,
    WEATHER_ID_BROKEN_CLOUDS,
    WEATHER_ID_OVERCAST_CLOUDS,
    WEATHER_ID_CALM
)